### PR TITLE
now compiles in nvcc 10.2

### PR DESCRIPTION
**Pull request by gridley**
So, using some xtensor stuff which uses variant.hpp, I was trying to unable to compile stuff with NVCC 10.2 (latest version), and encountered some parsing error in nvcc that is described in [this issue](https://github.com/xtensor-stack/xtl/issues/183) and this [PR](https://github.com/xtensor-stack/xtl/pull/184). It seems that part of the issue lies in xtensor-stack's xtl library and also this variant.hpp header file.

This PR just slightly changes an expression in variant.hpp so that the nvcc parser doesn't screw up. I think the code written here is valid beforehand, it's just that nvcc chokes on the parameter pack expansion somewhere.

The error which is encountered before this change, when including variant.hpp is:

```c++
gavin@gpad:~/scratch/variant/include/mpark$ nvcc nothing.cu 
variant.hpp: In function ‘constexpr decltype(auto) mpark::visit(Visitor&&, Vs&& ...)’:
variant.hpp:1967:96: error: parameter packs not expanded with ‘...’:
     return (detail::all({!vs.valueless_by_exception()...})
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                     ^                                                                                                      
variant.hpp:1967:96: note:         ‘vs’
```

No clue why this happens, but the changes here fix it.

### CODE REVIEW

**Comment by mpark** [comment]
What the heck...? Not sure why/how this got closed...

**Comment by mpark** [comment]
Oh~ it's because it's trying to merge into the `dev` branch, and I've been messing with the `dev` branch! @gridley Could you target this for `master` please?

**Comment by gridley** [comment]
Whoops, on it! My apologies!

**Comment by gridley** [comment]
@mpark OK, it's master now.

**Comment by mpark** [comment]
@gridley the changes seem much bigger than it was before. seems like there may have been formatting applied or something?

**Comment by gridley** [comment]
OK, so, *maybe* now this is ready once tests run.

**Comment by mpark** [comment]
Okay, I've fixed `master` and re-run the tests for this PR. @ax3l Could you confirm whether this works for you please?

**Comment by ax3l** [comment]
I am trying to confirm this fixes my issue as well, but have troubles since the HPC machine this was found with changed its software environment recently and I cannot reproduce the original issue on other machines yet. Trying to setup another machine today...

**Comment by ax3l** [comment]
Ok, I was now able to spin up another env that can reproduce the problem I reported. Sorry for the delay that this caused.
I can confirm the proposed fix in this PR works for me as well and we can close #71 in favour of it. Thanks a lot!

As a side note: I reported the NVCC compiler frontend issue in #70 to Nvidia too and it will be fixed in the next CUDA release as well (latest today: NVCC 10.2.89).
